### ISSUE TITLE
文件夹名称重复

### ISSUE THREAD

**Issue by meishaofeng1** [pxzxj/SVNLabel#1]
idea的svn插件拉到本地，再导入项目到idea，然后安装SVNLabel,然后发现所有文件夹名称均重复。

![image](https://user-images.githubusercontent.com/37138392/78970807-c3b69b00-7b3c-11ea-8496-0e56bd3c5d2f.png)

**Comment by pxzxj** [comment]
一般IDEA都是用电脑上装的TortoiseSVN拣出项目的，你如果是用其它SVN插件拣出是会有问题

**Comment by meishaofeng1** [comment]
都是直接IDEA里面的SVN插件，MAC和Linux都没有小乌龟。。现在插件不适配2020.1版本了，在IDEA中直接提示不适用了，有时间能修复下吗？
错误提示：Plugin Error: Plugin "SVNLabel" is incompatible (until build 193.SNAPSHOT < IU-201.6668.121).

**Comment by pxzxj** [comment]
已经发布新版本支持2020.1版本；
关于插件拣出问题是这样的，IDEA默认安装了Subversion插件用于SVN操作，但它依赖本机的SVN客户端，Windows通常安装TortoiseSVN，Mac上一定也有对应的客户端软件
文件夹名称重复应该是你除了默认的Subversion插件外还安装了其它用于展示svn信息的插件，例如SVNToolBox，它也会在Project View添加展示信息，跟SVNLabel展示的信息叠加了，这个没办法解决，只能保留一个

**Comment by meishaofeng1** [comment]
现在已经正常了，即使SVNToolBox和SVNLabel同时开启也没问题。非常感谢作者，能这么迅速的修复并适配新版本。辛苦了！

**Comment by pxzxj** [comment]
Problem has solved in new release
